version: "3"
services:
  bigip_explorer:
    image: nginx:latest
    build: .
    container_name: bigip_explorer
    ports:
      - 8082:8000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./worker.js:/etc/nginx/worker.js
      - ./portal:/etc/nginx/html/portal
    entrypoint: nginx